### ISSUE TITLE
[Feature request] – Gutenberg block

### ISSUE THREAD

**Issue by webliberty** [shazahm1/WP-Syntax#31]
Please update the plugin for compatibility with WordPress 5.0 and add the ability to insert code using a Gutenberg block.

**Comment by shazahm1** [comment]
Not sure this is going to happen... WP Syntax use geshi to process text and do the highlighting server side. In the Gutenberg world this does not work. Example you add you code to to a block but you would not see it highlighted until you save the page and view it on the frontend. Yes, I know this is exactly how this works with the classic editor, but the Gutenberg editor is supposed to be visual.

In addition, Gutenberg's own code block will begin highlighting code afte CodeMirror 6 has been completed and merged into WP.

**Comment by webliberty** [comment]
Thank you, I understood your thought, this is a logical explanation.

Probably the need for plugins will disappear after the introduction of CodeMirror 6.
